[package]
name = "visage-gui"
version.workspace = true
edition.workspace = true
license.workspace = true

description = "Graphical enrollment front-end for Visage (prototype)"

[[bin]]
name = "visage-enroll-gui"
path = "src/main.rs"

[dependencies]
visage-ipc = { path = "../visage-ipc" }
zbus = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
eframe = { workspace = true }
